export const therapistTypesData = [
  {
    typeName: "Psychology",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "Psychology",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "Psychology",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "Psychology",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "Psychology",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "Psychology",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "Psychology",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "Psychology",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "Psychology",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "Psychology",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "Psychology",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "Social Worker",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "Social Worker",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "Social Worker",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "Social Worker",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "Social Worker",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "Social Worker",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "Social Worker",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "Social Worker",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "Social Worker",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "Social Worker",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "Social Worker",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "Criminologiest",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "Criminologiest",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "Criminologiest",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "Criminologiest",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "Criminologiest",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "Criminologiest",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "Criminologiest",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "Criminologiest",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "Criminologiest",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "Criminologiest",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "Criminologiest",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "Creative Arts Therapist",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "Creative Arts Therapist",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "Creative Arts Therapist",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "Creative Arts Therapist",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "Creative Arts Therapist",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "Creative Arts Therapist",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "Creative Arts Therapist",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "Creative Arts Therapist",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "Creative Arts Therapist",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "Creative Arts Therapist",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "Creative Arts Therapist",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "Psychodrama Therapist",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "Psychodrama Therapist",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "Psychodrama Therapist",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "Psychodrama Therapist",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "Psychodrama Therapist",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "Psychodrama Therapist",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "Psychodrama Therapist",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "Psychodrama Therapist",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "Psychodrama Therapist",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "Psychodrama Therapist",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "Psychodrama Therapist",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "Bibliotherapist",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "Bibliotherapist",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "Bibliotherapist",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "Bibliotherapist",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "Bibliotherapist",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "Bibliotherapist",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "Bibliotherapist",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "Bibliotherapist",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "Bibliotherapist",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "Bibliotherapist",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "Bibliotherapist",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "Occupational Therapist",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "Occupational Therapist",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "Occupational Therapist",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "Occupational Therapist",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "Occupational Therapist",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "Occupational Therapist",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "Occupational Therapist",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "Occupational Therapist",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "Occupational Therapist",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "Occupational Therapist",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "Occupational Therapist",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "Speach Therapist",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "Speach Therapist",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "Speach Therapist",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "Speach Therapist",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "Speach Therapist",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "Speach Therapist",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "Speach Therapist",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "Speach Therapist",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "Speach Therapist",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "Speach Therapist",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "Speach Therapist",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "Psycho Therapist",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "Psycho Therapist",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "Psycho Therapist",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "Psycho Therapist",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "Psycho Therapist",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "Psycho Therapist",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "Psycho Therapist",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "Psycho Therapist",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "Psycho Therapist",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "Psycho Therapist",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "Psycho Therapist",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "CBT Therapist",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "CBT Therapist",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "CBT Therapist",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "CBT Therapist",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "CBT Therapist",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "CBT Therapist",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "CBT Therapist",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "CBT Therapist",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "CBT Therapist",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "CBT Therapist",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "CBT Therapist",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "DBT Therapist",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "DBT Therapist",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "DBT Therapist",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "DBT Therapist",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "DBT Therapist",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "DBT Therapist",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "DBT Therapist",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "DBT Therapist",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "DBT Therapist",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "DBT Therapist",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "DBT Therapist",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "NLP Therapist",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "NLP Therapist",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "NLP Therapist",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "NLP Therapist",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "NLP Therapist",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "NLP Therapist",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "NLP Therapist",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "NLP Therapist",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "NLP Therapist",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "NLP Therapist",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "NLP Therapist",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "EMDR Therapist",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "EMDR Therapist",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "EMDR Therapist",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "EMDR Therapist",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "EMDR Therapist",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "EMDR Therapist",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "EMDR Therapist",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "EMDR Therapist",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "EMDR Therapist",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "EMDR Therapist",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "EMDR Therapist",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "Animal-Assisted Therapist",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "Animal-Assisted Therapist",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "Animal-Assisted Therapist",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "Animal-Assisted Therapist",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "Animal-Assisted Therapist",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "Animal-Assisted Therapist",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "Animal-Assisted Therapist",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "Animal-Assisted Therapist",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "Animal-Assisted Therapist",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "Animal-Assisted Therapist",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "Animal-Assisted Therapist",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "Neurofeedback",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "Neurofeedback",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "Neurofeedback",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "Neurofeedback",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "Neurofeedback",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "Neurofeedback",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "Neurofeedback",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "Neurofeedback",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "Neurofeedback",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "Neurofeedback",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "Neurofeedback",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "Psychoanaliest",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "Psychoanaliest",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "Psychoanaliest",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "Psychoanaliest",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "Psychoanaliest",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "Psychoanaliest",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "Psychoanaliest",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "Psychoanaliest",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "Psychoanaliest",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "Psychoanaliest",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "Psychoanaliest",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "Psychiatrist",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "Psychiatrist",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "Psychiatrist",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "Psychiatrist",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "Psychiatrist",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "Psychiatrist",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "Psychiatrist",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "Psychiatrist",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "Psychiatrist",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "Psychiatrist",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "Psychiatrist",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "Family Therapist",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "Family Therapist",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "Family Therapist",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "Family Therapist",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "Family Therapist",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "Family Therapist",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "Family Therapist",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "Family Therapist",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "Family Therapist",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "Family Therapist",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "Family Therapist",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "Caple Therapist",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "Caple Therapist",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "Caple Therapist",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "Caple Therapist",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "Caple Therapist",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "Caple Therapist",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "Caple Therapist",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "Caple Therapist",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "Caple Therapist",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "Caple Therapist",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "Caple Therapist",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
  {
    typeName: "Dance Therapisty",
    users: [
      {
        id: 1,
        name: "Leanne Graham",
        typeName: "Dance Therapisty",
        email: "Sincere@april.biz",
        address: {
          street: "Kulas Light",
          city: "Tel-Aviv",
        },
        phone: "1-770-736-8031 x56442",
        price: 200,
        gender: "female",
        language: ["hebrew", "english", "russian", "arabic"],
        experience: 5,
        LGBTQ: true,
      },
      {
        id: 2,
        name: "Ervin Howell",
        typeName: "Dance Therapisty",
        email: "Shanna@melissa.tv",
        address: {
          street: "Victor Plains",
          city: "Ramat-Gan",
        },
        phone: "010-692-6593 x09125",
        price: 250,
        gender: "male",
        language: ["hebrew"],
        experience: 1,
        LGBTQ: true,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        typeName: "Dance Therapisty",
        email: "Nathan@yesenia.net",
        address: {
          street: "Douglas Extension",
          city: "Ashkelon",
        },
        phone: "1-463-123-4447",
        price: 100,
        gender: "female",
        language: ["hebrew", "english"],
        experience: 3,
        LGBTQ: true,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        typeName: "Dance Therapisty",
        email: "Julianne.OConner@kory.org",
        address: {
          street: "Hoeger Mall",
          city: "Haifa",
        },
        phone: "493-170-9623 x156",
        price: 50,
        gender: "female",
        language: ["english", "russian"],
        experience: 10,
        LGBTQ: false,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        typeName: "Dance Therapisty",
        email: "Lucio_Hettinger@annie.ca",
        address: {
          street: "Skiles Walks",
          city: "Ashdod",
        },
        phone: "(254)954-1289",
        price: 400,
        gender: "male",
        language: ["hebrew", "russian"],
        experience: 15,
        LGBTQ: false,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        typeName: "Dance Therapisty",
        email: "Karley_Dach@jasper.info",
        address: {
          street: "Norberto Crossing",
          city: "Raanana",
        },
        phone: "1-477-935-8478 x6430",
        price: 450,
        gender: "female",
        language: ["english"],
        experience: 20,
        LGBTQ: true,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        typeName: "Dance Therapisty",
        email: "Telly.Hoeger@billy.biz",
        address: {
          street: "Rex Trail",
          city: "Rehovot",
        },
        phone: "210.067.6132",
        price: 400,
        gender: "male",
        language: ["hebrew", "arabic"],
        experience: 25,
        LGBTQ: false,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        typeName: "Dance Therapisty",
        email: "Sherwood@rosamond.me",
        address: {
          street: "Ellsworth Summit",
          city: "Nahariya",
        },
        phone: "586.493.6943 x140",
        price: 300,
        gender: "male",
        language: ["arabic"],
        experience: 15,
        LGBTQ: true,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        typeName: "Dance Therapisty",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        address: {
          street: "Dayna Park",
          city: "Kiryat-Shmona",
        },
        phone: "(775)976-6794 x41206",
        price: 220,
        gender: "female",
        language: ["hebrew"],
        experience: 7,
        LGBTQ: false,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        typeName: "Dance Therapisty",
        email: "Rey.Padberg@karina.biz",
        address: {
          street: "Kattie Turnpike",
          city: "Eilat",
        },
        phone: "024-648-3804",
        price: 250,
        gender: "male",
        language: ["hebrew", "english", "russian"],
        experience: 8,
        LGBTQ: true,
      },
    ],
  },
];

const allUsers = [];
therapistTypesData.map((therapistType) => {
  let users = therapistType.users;
  users.map((user) => {
    allUsers.push(user);
  });
});

export { allUsers };
