export const professions = [
  "Psychologist",
  "Social Worker",
  "Occupational Therapist",
  "Speach Therapist",
  "Art Therapist",
  "Couple Therapist",
  "Cognitive Behavioral Therapist",
  "Psychotherapist"
];

export const experties = [
  "Creative Arts Therapy",
  "Psychodrama Therapy",
  "Bibliotherapist",
  "CBT Therapy",
  "DBT Therapy",
  "EMDR Therapy",
  "ACT Therapy",
  "NLP Therapy",        
  "Coaching",
  "Animal-Assisted Therapy",
  "Neurofeedback",
  "Psychoanalysis",
  "Family Therapy",
  "Caple Therapy",
  "Sexual Therapy",
  "Guided Imagery/Visualization",
  "Parental Guidance",
  "Psychotherapy",
  "Biofeedback",
  "Sleep Disorder",
  "Eating Disorder",
  "Emotional Eating",               
  "Depression",
  "Divorcement",      
  "ADHD",
  "Anxiety Disorders",
  "PTSD",
  "Personality Disorder",
  "Addiction",
  "Mindfulness",
  "Psychotic Disorders",
  "Mood Disorders",
  "OCD",
  "PDD/ASD",
];

export const cities = [
  { City: "ABU JUWEI'ID " },
  { City: "ABU GHOSH " },
  { City: "ABU SINAN " },
  { City: "ABU SUREIHAN " },
  { City: "ABU ABDUN " },
  { City: "ABU AMMAR " },
  { City: "ABU AMRE " },
  { City: "ABU QUREINAT " },
  { City: "ABU QUREINAT " },
  { City: "ABU RUBEI'A " },
  { City: "ABU RUQAYYEQ " },
  { City: " " },
  { City: "IBTIN " },
  { City: "AVTALYON " },
  { City: "AVI'EL " },
  { City: "AVIVIM " },
  { City: "AVIGEDOR " },
  { City: "AVIHAYIL " },
  { City: "AVITAL " },
  { City: "AVI'EZER " },
  { City: "ABBIRIM " },
  { City: "EVEN YEHUDA " },
  { City: "EVEN MENAHEM " },
  { City: "EVEN SAPPIR " },
  { City: "EVEN SHEMU'EL " },
  { City: "AVNE ETAN " },
  { City: "AVNE HEFEZ " },
  { City: "AVENAT " },
  { City: "AVSHALOM " },
  { City: "ADORA " },
  { City: "ADDIRIM " },
  { City: "ADAMIT " },
  { City: "ADDERET " },
  { City: "UDIM " },
  { City: "ODEM " },
  { City: "OHAD " },
  { City: "UMM AL-FAHM " },
  { City: "UMM AL-QUTUF " },
  { City: " " },
  { City: "OMEN " },
  { City: "OMEZ " },
  { City: "OFAQIM " },
  { City: "OR HAGANUZ " },
  { City: "OR HANER " },
  { City: "OR YEHUDA " },
  { City: "OR AQIVA " },
  { City: "ORA " },
  { City: "OROT " },
  { City: "ORTAL " },
  { City: "URIM " },
  { City: "ORANIM " },
  { City: "ORANIT " },
  { City: "USHA " },
  { City: "AZOR " },
  { City: "AHAWA " },
  { City: "AHUZZAM " },
  { City: " " },
  { City: "AHIHUD " },
  { City: "AHITUV " },
  { City: "AHISAMAKH " },
  { City: "AHI'EZER " },
  { City: "ATRASH " },
  { City: "IBBIM " },
  { City: "EYAL " },
  { City: "AYYELET HASHAHAR " },
  { City: "ELON " },
  { City: "ELOT " },
  { City: "ILANIYYA " },
  { City: "ELAT " },
  { City: " " },
  { City: "ITAMAR " },
  { City: "ETAN " },
  { City: "ETANIM " },
  { City: "IKSAL " },
  { City: " " },
  { City: " " },
  { City: "AL-ARYAN " },
  { City: "EL-ROM " },
  { City: "ALUMMA " },
  { City: "ALUMMOT " },
  { City: "ALLON HAGALIL " },
  { City: "ELON MORE " },
  { City: "ALLON SHEVUT " },
  { City: "ALLONE ABBA " },
  { City: "ALLONE HABASHAN " },
  { City: "ALLONE YIZHAQ " },
  { City: "ALLONIM " },
  { City: "ELI AL " },
  { City: " " },
  { City: "ELYAKHIN " },
  { City: "ELIFAZ " },
  { City: "ELIFELET " },
  { City: "ELYAQIM " },
  { City: "ELYASHIV " },
  { City: "ELISHAMA " },
  { City: "ALMAGOR " },
  { City: "ALMOG " },
  { City: " " },
  { City: "EL'AZAR " },
  { City: "ALFE MENASHE " },
  { City: "ELQOSH " },
  { City: "ELQANA " },
  { City: "EMUNIM " },
  { City: "AMIRIM " },
  { City: "AMNUN " },
  { City: "AMAZYA " },
  { City: "ANI'AM " },
  { City: "ASAD " },
  { City: "ASEFAR " },
  { City: "I'BILLIN " },
  { City: "A'SAM " },
  { City: "AFEINISH " },
  { City: "AFIQ " },
  { City: "AFIQIM " },
  { City: "AFEQ " },
  { City: "EFRATA " },
  { City: "ARBEL " },
  { City: "ARGAMAN " },
  { City: "EREZ " },
  { City: "ARI'EL " },
  { City: "ARSUF " },
  { City: "ESHBOL " },
  { City: "NAHAL ESHBAL " },
  { City: "ASHDOD " },
  { City: "ASHDOT YA'AQOV(IHUD) " },
  { City: "ASHDOT YA'AQOV(ME'UH " },
  { City: "ESHHAR " },
  { City: "ESHKOLOT " },
  { City: "ESHEL HANASI " },
  { City: "ASHALIM " },
  { City: "ASHQELON " },
  { City: "ASHERAT " },
  { City: "ESHTA'OL " },
  { City: "ETGAR " },
  { City: " " },
  { City: "BE'ER ORA " },
  { City: " " },
  { City: "BE'ER TUVEYA " },
  { City: "BE'ER YA'AQOV " },
  { City: " " },
  { City: "BE'ER SHEVA " },
  { City: "BE'EROT YIZHAQ " },
  { City: "BE'EROTAYIM " },
  { City: "BE'ERI " },
  { City: "BUSTAN HAGALIL " },
  { City: "BU'EINE-NUJEIDAT " },
  { City: "BUQ'ATA " },
  { City: "BURGETA " },
  { City: "BAHAN " },
  { City: "BITHA " },
  { City: "BIZZARON " },
  { City: "BIR EL-MAKSUR " },
  { City: " " },
  { City: "BIRIYYA " },
  { City: "BET OREN " },
  { City: "BET EL " },
  { City: "BET EL'AZARI " },
  { City: "BET ALFA " },
  { City: "BET ARYE " },
  { City: "BET BERL " },
  { City: "BEIT JANN " },
  { City: "BET GUVRIN " },
  { City: "BET GAMLI'EL " },
  { City: "BET DAGAN " },
  { City: "BET HAGADDI " },
  { City: "BET HALEVI " },
  { City: "BET HILLEL " },
  { City: "BET HAEMEQ " },
  { City: "BET HAARAVA " },
  { City: "BET HASHITTA " },
  { City: "BET ZEID " },
  { City: "BET ZAYIT " },
  { City: "BET ZERA " },
  { City: "BET HORON " },
  { City: "BET HERUT " },
  { City: "BET HILQIYYA " },
  { City: "BET HANAN " },
  { City: "BET HANANYA " },
  { City: "BET HASHMONAY " },
  { City: "BET YEHOSHUA " },
  { City: "BET YOSEF " },
  { City: "BET YANNAY " },
  { City: "BET YIZHAQ-SH. HEFER " },
  { City: "BET LEHEM HAGELILIT " },
  { City: "BET ME'IR " },
  { City: "BET NEHEMYA " },
  { City: "BET NIR " },
  { City: "BET NEQOFA " },
  { City: "BET OVED " },
  { City: "BET UZZI'EL " },
  { City: "BET EZRA " },
  { City: "BET ARIF " },
  { City: "BET ZEVI " },
  { City: "BET QAMA " },
  { City: "BET QESHET " },
  { City: "BET RABBAN " },
  { City: "BET RIMMON " },
  { City: "BET SHE'AN " },
  { City: "BET SHEMESH " },
  { City: "BET SHE'ARIM " },
  { City: "BET SHIQMA " },
  { City: "BITAN AHARON " },
  { City: "BETAR ILLIT " },
  { City: "BALFURIYYA " },
  { City: "BEN ZAKKAY " },
  { City: "BEN AMMI " },
  { City: "BEN SHEMEN(K.NO'AR) " },
  { City: "BEN SHEMEN (MOSHAV) " },
  { City: "BENE BERAQ " },
  { City: "BNE DKALIM " },
  { City: "BENE DAROM " },
  { City: "BENE DEROR " },
  { City: "BENE YEHUDA " },
  { City: "BENE NEZARIM " },
  { City: "BENE ATAROT " },
  { City: "BENE AYISH " },
  { City: "BENE ZIYYON " },
  { City: "BENE RE'EM " },
  { City: "BENAYA " },
  { City: "BINYAMINA " },
  { City: "BASMA " },
  { City: "BASMAT TAB'UN " },
  { City: "BI NE " },
  { City: "BAZRA " },
  { City: "BEZET " },
  { City: "BEQOA " },
  { City: "BEQA'OT " },
  { City: "BAR GIYYORA " },
  { City: "BAR YOHAY " },
  { City: " " },
  { City: "BEROR HAYIL " },
  { City: "BEROSH " },
  { City: "BERAKHA " },
  { City: "BEREKHYA " },
  { City: "BAR'AM " },
  { City: "BARAQ " },
  { City: "BARQAY " },
  { City: "BARQAN " },
  { City: "BAREQET " },
  { City: "BAT HADAR " },
  { City: "BAT HEN " },
  { City: "BAT HEFER " },
  { City: "BAT HAZOR " },
  { City: "BAT YAM " },
  { City: "BAT AYIN " },
  { City: "BAT SHELOMO " },
  { City: "JUDEIDE-MAKER " },
  { City: "JULIS " },
  { City: "JALJULYE " },
  { City: "JUNNABIB " },
  { City: "JISR AZ-ZARQA " },
  { City: "JISH(GUSH HALAV) " },
  { City: "JAAT " },
  { City: "GE'ULE TEMAN " },
  { City: "GE'ULIM " },
  { City: "GE'ALYA " },
  { City: "GEVULOT " },
  { City: "GEVIM " },
  { City: "GEVA " },
  { City: "GEVA BINYAMIN " },
  { City: "GEVA KARMEL " },
  { City: "GIV'OLIM " },
  { City: "GIV'ON HAHADASHA " },
  { City: " " },
  { City: "GIV'AT AVNI " },
  { City: "GIV'AT ELA " },
  { City: "GIV'AT BRENNER " },
  { City: "GIV'AT HASHELOSHA " },
  { City: "GIV'AT ZE'EV " },
  { City: "GIV'AT HEN " },
  { City: "GIV'AT HAYYIM (IHUD) " },
  { City: "GIV'AT HAYYIM(ME'UHA " },
  { City: "GIV'AT YO'AV " },
  { City: "GIV'AT YE'ARIM " },
  { City: "GIV'AT YESHA'YAHU " },
  { City: "GIV'AT KOAH " },
  { City: "GIV'AT NILI " },
  { City: "GIV'AT OZ " },
  { City: "GIV'AT SHEMU'EL " },
  { City: "GIV'AT SHEMESH " },
  { City: "GIV'AT SHAPPIRA " },
  { City: "GIV'ATI " },
  { City: "GIV'ATAYIM " },
  { City: "GEVAR'AM " },
  { City: "GEVAT " },
  { City: "GADOT " },
  { City: "GADISH " },
  { City: "GID'ONA " },
  { City: "GEDERA " },
  { City: "GONEN " },
  { City: "GOREN " },
  { City: "GORNOT HAGALIL " },
  { City: "GAZIT " },
  { City: "GEZER " },
  { City: "GE'A " },
  { City: "GIBBETON " },
  { City: "GIZO " },
  { City: "GILON " },
  { City: "GILAT " },
  { City: "GINNOSAR " },
  { City: "GINNEGAR " },
  { City: "GINNATON " },
  { City: "GITTA " },
  { City: "GITTIT " },
  { City: "GAL'ON " },
  { City: "GILGAL " },
  { City: "GELIL YAM " },
  { City: "EVEN YIZHAQ(GAL'ED) " },
  { City: "GIMZO " },
  { City: "GAN HADAROM " },
  { City: "GAN HASHOMERON " },
  { City: "GAN HAYYIM " },
  { City: "GAN YOSHIYYA " },
  { City: "GAN YAVNE " },
  { City: "GAN NER " },
  { City: "GAN SOREQ " },
  { City: "GAN SHELOMO " },
  { City: "GAN SHEMU'EL " },
  { City: "GANNOT " },
  { City: "GANNOT HADAR " },
  { City: "GANNE HADAR " },
  { City: " " },
  { City: "GANNE YOHANAN " },
  { City: " " },
  { City: "GANNE AM " },
  { City: "GANNE TIQWA " },
  { City: "GA'ASH " },
  { City: "GA'TON " },
  { City: "GEFEN " },
  { City: "GEROFIT " },
  { City: "GESHUR " },
  { City: "GESHER " },
  { City: "GESHER HAZIW " },
  { City: "GAT(QIBBUZ) " },
  { City: "GAT RIMMON " },
  { City: "DALIYAT AL-KARMEL " },
  { City: "DEVORA " },
  { City: "DABBURYE " },
  { City: "DEVIRA " },
  { City: "DAVERAT " },
  { City: "DEGANYA ALEF " },
  { City: "DEGANYA BET " },
  { City: "DOVEV " },
  { City: "DOLEV " },
  { City: "DOR " },
  { City: "DOROT " },
  { City: "DAHI " },
  { City: "DEIR AL-ASAD " },
  { City: "DEIR HANNA " },
  { City: "DEIR RAFAT " },
  { City: "DIMONA " },
  { City: "DISHON " },
  { City: "DALIYYA " },
  { City: "DALTON " },
  { City: "DEMEIDE " },
  { City: "DAN " },
  { City: "DAFNA " },
  { City: "DEQEL " },
  { City: " " },
  { City: "HAON " },
  { City: "HABONIM " },
  { City: "HAGOSHERIM " },
  { City: "HADAR AM " },
  { City: "HOD HASHARON " },
  { City: "HODIYYA " },
  { City: "HODAYOT " },
  { City: "HAWASHLA " },
  { City: "HUZAYYEL " },
  { City: "HOSHA'AYA " },
  { City: "HAZOREA " },
  { City: "HAZORE'IM " },
  { City: "HAHOTERIM " },
  { City: "HAYOGEV " },
  { City: "HILLA " },
  { City: "HAMA'PIL " },
  { City: "HASOLELIM " },
  { City: "HAOGEN " },
  { City: "HAR ADAR " },
  { City: "HAR GILLO " },
  { City: "HAR AMASA " },
  { City: "HAR'EL " },
  { City: "HARDUF " },
  { City: "HERZELIYYA " },
  { City: "HARARIT " },
  { City: "WERED YERIHO " },
  { City: "WARDON " },
  { City: "ZABARGA " },
  { City: "ZAVDI'EL " },
  { City: "ZOHAR " },
  { City: "ZIQIM " },
  { City: "ZETAN " },
  { City: "ZIKHRON YA'AQOV " },
  { City: "ZEKHARYA " },
  { City: "ZEMER " },
  { City: "ZIMRAT " },
  { City: "ZANOAH " },
  { City: "ZERU'A " },
  { City: "ZARZIR " },
  { City: "ZERAHYA " },
  { City: " " },
  { City: "KHAWALED " },
  { City: "HAVAZZELET HASHARON " },
  { City: "HEVER " },
  { City: " " },
  { City: "HAGOR " },
  { City: "HAGGAI " },
  { City: "HOGLA " },
  { City: "HAD-NES " },
  { City: "HADID " },
  { City: "HADERA " },
  { City: "HUJEIRAT (DAHRA) " },
  { City: "HULDA " },
  { City: "HOLON " },
  { City: "HOLIT " },
  { City: "HULATA " },
  { City: "HOSEN " },
  { City: "HUSSNIYYA " },
  { City: "HOFIT " },
  { City: "HUQOQ " },
  { City: "HURA " },
  { City: "HURFEISH " },
  { City: "HORESHIM " },
  { City: "HAZON " },
  { City: "HIBBAT ZIYYON " },
  { City: "HINNANIT " },
  { City: "HAIFA " },
  { City: "HERUT " },
  { City: "HALUZ " },
  { City: "HELEZ " },
  { City: "HAMAM " },
  { City: "HEMED " },
  { City: "HAMADYA " },
  { City: "NAHAL HEMDAT " },
  { City: "HAMRA  " },
  { City: "HANNI'EL " },
  { City: "HANITA " },
  { City: "HANNATON " },
  { City: "HASPIN " },
  { City: "HAFEZ HAYYIM " },
  { City: "HEFZI-BAH " },
  { City: "HAZAV " },
  { City: "HAZEVA " },
  { City: "HAZOR HAGELILIT " },
  { City: "HAZOR-ASHDOD " },
  { City: "HAZAR BE'EROTAYIM " },
  { City: "HAZROT HULDA " },
  { City: "HAZROT YASAF " },
  { City: "HAZROT KOAH " },
  { City: "HAZERIM " },
  { City: "HEREV LE'ET " },
  { City: "HARUZIM " },
  { City: "HARISH " },
  { City: "HERMESH " },
  { City: "HARASHIM " },
  { City: "HASHMONA'IM " },
  { City: "TIBERIAS " },
  { City: "TUBA-ZANGARIYYE " },
  { City: "TUR'AN " },
  { City: "TAYIBE " },
  { City: "TAYIBE(BAEMEQ) " },
  { City: "TIRE " },
  { City: "TIRAT YEHUDA " },
  { City: "TIRAT KARMEL " },
  { City: "TIRAT ZEVI " },
  { City: "TAL SHAHAR " },
  { City: "TAL-EL " },
  { City: "TELALIM " },
  { City: "TALMON " },
  { City: "TAMRA " },
  { City: "TAMRA (YIZRE'EL) " },
  { City: "TENE " },
  { City: "TEFAHOT " },
  { City: "YANUH-JAT " },
  { City: "YEVUL " },
  { City: "YAVNE'EL " },
  { City: "YAVNE " },
  { City: "YAGUR " },
  { City: "YAGEL " },
  { City: "YAD BINYAMIN " },
  { City: "YAD HASHEMONA " },
  { City: "YAD HANNA " },
  { City: "YAD MORDEKHAY " },
  { City: "YAD NATAN " },
  { City: "YAD RAMBAM " },
  { City: "YEDIDA " },
  { City: "YEHUD-MONOSON " },
  { City: "YAHEL " },
  { City: "YUVAL " },
  { City: "YUVALIM " },
  { City: "YODEFAT " },
  { City: "YONATAN " },
  { City: "YOSHIVYA " },
  { City: "YIZRE'EL " },
  { City: "YEHI'AM " },
  { City: "YOTVATA " },
  { City: "YITAV " },
  { City: "YAKHINI " },
  { City: "YANUV  " },
  { City: "YINNON " },
  { City: "YESUD HAMA'ALA " },
  { City: "YESODOT " },
  { City: "YAS'UR " },
  { City: "YA'AD " },
  { City: "YA'EL " },
  { City: "YE'AF " },
  { City: "YA'ARA " },
  { City: "YAFI " },
  { City: "YAFIT " },
  { City: "YIF'AT " },
  { City: "YIFTAH " },
  { City: "YIZHAR " },
  { City: "YAZIZ " },
  { City: "YAQUM " },
  { City: "YAQIR " },
  { City: "YOQNE'AM(MOSHAVA) " },
  { City: "YOQNE'AM ILLIT " },
  { City: "YIR'ON " },
  { City: "YARDENA " },
  { City: "YEROHAM " },
  { City: "JERUSALEM " },
  { City: "YARHIV " },
  { City: "YIRKA " },
  { City: "YARQONA " },
  { City: "YESHA " },
  { City: "YISH'I " },
  { City: "YASHRESH " },
  { City: "YATED " },
  { City: " " },
  { City: "KABUL " },
  { City: "KAOKAB ABU AL-HIJA " },
  { City: "KABRI " },
  { City: "KADOORIE " },
  { City: " " },
  { City: "KOKHAV HASHAHAR " },
  { City: "KOKHAV YA'IR " },
  { City: "KOKHAV YA'AQOV " },
  { City: "KOKHAV MIKHA'EL " },
  { City: "KORAZIM " },
  { City: "KAHAL " },
  { City: " " },
  { City: "KISSUFIM " },
  { City: "KISHOR " },
  { City: "KELIL " },
  { City: "KALLANIT " },
  { City: " " },
  { City: "KEMEHIN " },
  { City: "KAMMON " },
  { City: "KANNOT " },
  { City: "KANAF " },
  { City: "KINNERET(MOSHAVA) " },
  { City: "KINNERET(QEVUZA) " },
  { City: "KUSEIFE " },
  { City: "KESALON " },
  { City: "KISRA-SUMEI " },
  { City: "KA'ABIYYE-TABBASH-HA " },
  { City: "KEFAR AVIV " },
  { City: "KEFAR ADUMMIM " },
  { City: "KEFAR URIYYA " },
  { City: "KEFAR AHIM " },
  { City: "KEFAR BIALIK " },
  { City: "KEFAR BILU " },
  { City: "KEFAR BLUM " },
  { City: "KEFAR BIN NUN " },
  { City: "KAFAR BARA " },
  { City: "KEFAR BARUKH " },
  { City: "KEFAR GID'ON " },
  { City: "KEFAR GALLIM " },
  { City: "KEFAR GLIKSON " },
  { City: "KEFAR GIL'ADI " },
  { City: "KEFAR DANIYYEL " },
  { City: "KEFAR HAORANIM " },
  { City: "KEFAR HAHORESH " },
  { City: "KEFAR HAMAKKABI " },
  { City: "KEFAR HANAGID " },
  { City: "KEFAR HANO'AR HADATI " },
  { City: "KEFAR HANASI " },
  { City: "KEFAR HESS " },
  { City: "KEFAR HARO'E " },
  { City: "KEFAR HARIF " },
  { City: "KEFAR VITKIN " },
  { City: "KEFAR WARBURG " },
  { City: "KEFAR WERADIM " },
  { City: "KEFAR ZOHARIM " },
  { City: "KEFAR ZETIM " },
  { City: "KEFAR HABAD " },
  { City: "KEFAR HOSHEN " },
  { City: "KEFAR HITTIM " },
  { City: "KEFAR HAYYIM " },
  { City: "KEFAR HANANYA " },
  { City: "KEFAR HASIDIM ALEF " },
  { City: "KEFAR HASIDIM BET " },
  { City: "KEFAR HARUV " },
  { City: "KEFAR TRUMAN " },
  { City: "KAFAR YASIF " },
  { City: "YEDIDYA " },
  { City: "KEFAR YEHOSHUA " },
  { City: "KEFAR YONA " },
  { City: "KEFAR YEHEZQEL " },
  { City: "KEFAR YA'BEZ " },
  { City: "KAFAR KAMA " },
  { City: "KAFAR KANNA " },
  { City: "KEFAR MONASH " },
  { City: "KEFAR MAYMON " },
  { City: "KEFAR MALAL " },
  { City: "KAFAR MANDA " },
  { City: "KEFAR MENAHEM " },
  { City: "KEFAR MASARYK " },
  { City: "KAFAR MISR " },
  { City: "KEFAR MORDEKHAY " },
  { City: "KEFAR NETTER " },
  { City: "KEFAR SZOLD " },
  { City: "KEFAR SAVA " },
  { City: "KEFAR SILVER " },
  { City: "KEFAR SIRKIN " },
  { City: "KEFAR AVODA " },
  { City: "KEFAR AZZA " },
  { City: "KEFAR EZYON " },
  { City: "KEFAR PINES " },
  { City: "KAFAR QASEM " },
  { City: "KEFAR KISH " },
  { City: "KAFAR QARA " },
  { City: "KEFAR ROSH HANIQRA " },
  { City: "KEFAR ROZENWALD(ZAR. " },
  { City: "KEFAR RUPPIN " },
  { City: "KEFAR RUT " },
  { City: "KEFAR SHAMMAY " },
  { City: "KEFAR SHEMU'EL " },
  { City: "KEFAR SHEMARYAHU " },
  { City: "KEFAR TAVOR " },
  { City: "KEFAR TAPPUAH " },
  { City: "KARE DESHE " },
  { City: "KARKOM " },
  { City: "KEREM BEN ZIMRA " },
  { City: "KEREM BEN SHEMEN " },
  { City: "KEREM YAVNE(YESHIVA) " },
  { City: "KEREM MAHARAL " },
  { City: "KEREM SHALOM " },
  { City: "KARME YOSEF " },
  { City: "KARME ZUR " },
  { City: " " },
  { City: "KARMI'EL " },
  { City: "KARMIYYA " },
  { City: "KERAMIM " },
  { City: "KARMEL " },
  { City: " " },
  { City: "LAVON " },
  { City: "LAVI " },
  { City: "LIVNIM " },
  { City: "LAHAV " },
  { City: "LAHAVOT HABASHAN " },
  { City: "LAHAVOT HAVIVA " },
  { City: "LEHAVIM " },
  { City: "LOD " },
  { City: "LUZIT " },
  { City: "LOHAME HAGETA'OT " },
  { City: "LOTEM " },
  { City: "LOTAN " },
  { City: "LIMAN " },
  { City: "LAKHISH " },
  { City: "LAPPID " },
  { City: "LAPPIDOT " },
  { City: "LAQYE " },
  { City: "MA'OR " },
  { City: "ME'IR SHEFEYA " },
  { City: "MEVO BETAR " },
  { City: "MEVO DOTAN " },
  { City: "MEVO HORON " },
  { City: "MEVO HAMMA " },
  { City: "MEVO MODI'IM " },
  { City: "MEVO'OT YAM " },
  { City: " " },
  { City: "MABBU'IM " },
  { City: "MIVTAHIM " },
  { City: "MAVQI'IM " },
  { City: "MEVASSERET ZIYYON " },
  { City: "MAJD AL-KURUM " },
  { City: "MAJDAL SHAMS " },
  { City: "MUGHAR " },
  { City: "MEGADIM " },
  { City: "MIGDAL " },
  { City: "MIGDAL HAEMEQ " },
  { City: "MIGDAL OZ " },
  { City: "MIGDALIM " },
  { City: "MEGIDDO " },
  { City: "MAGGAL " },
  { City: "MAGEN " },
  { City: "MAGEN SHA'UL " },
  { City: "MAGSHIMIM " },
  { City: "MIDRAKH OZ " },
  { City: "MIDRESHET BEN GURION " },
  { City: "MIDRESHET RUPPIN " },
  { City: "MODI'IN ILLIT " },
  { City: "MODI'IN-MAKKABBIM-RE " },
  { City: "MOLEDET " },
  { City: "MOZA ILLIT " },
  { City: "MUQEIBLE " },
  { City: "MORAN " },
  { City: "MORESHET " },
  { City: "MAZOR " },
  { City: "MAZKERET BATYA " },
  { City: "MIZRA " },
  { City: "MAZRA'A " },
  { City: "MEHOLA " },
  { City: " " },
  { City: " " },
  { City: " " },
  { City: " " },
  { City: " " },
  { City: "MAHANE YATTIR " },
  { City: " " },
  { City: " " },
  { City: "MAHANAYIM " },
  { City: "MAHSEYA " },
  { City: "METULA " },
  { City: "MATTA " },
  { City: "ME AMMI " },
  { City: "METAV " },
  { City: "MEISER " },
  { City: "MEZAR " },
  { City: "MERAV " },
  { City: "MERON " },
  { City: "MESHAR " },
  { City: "METAR " },
  { City: "MEKHORA " },
  { City: "MAKCHUL " },
  { City: "MIKHMORET " },
  { City: "MIKHMANNIM " },
  { City: "MELE'A " },
  { City: "MELILOT " },
  { City: "MALKIYYA " },
  { City: "MALKISHUA " },
  { City: "MENUHA " },
  { City: "MANOF " },
  { City: "MANOT " },
  { City: "MENAHEMYA " },
  { City: "MENNARA " },
  { City: "MANSHIYYET ZABDA " },
  { City: "MASSAD " },
  { City: "MASSADA " },
  { City: "MESILLOT " },
  { City: "MESILLAT ZIYYON " },
  { City: "MASLUL " },
  { City: "MAS'ADE " },
  { City: "MAS'UDIN AL-'AZAZME " },
  { City: "MA'BAROT " },
  { City: "MA'GALIM " },
  { City: "MA'AGAN " },
  { City: "MA'AGAN MIKHA'EL " },
  { City: "MA'OZ HAYYIM " },
  { City: "MA'ON " },
  { City: "ME'ONA " },
  { City: "MI'ELYA " },
  { City: "MA'YAN BARUKH " },
  { City: "MA'YAN ZEVI " },
  { City: "MA'ALE ADUMMIM " },
  { City: "MA'ALE EFRAYIM " },
  { City: "MA'ALE GILBOA " },
  { City: "MA'ALE GAMLA " },
  { City: "MA'ALE HAHAMISHA " },
  { City: "MA'ALE LEVONA " },
  { City: "MA'ALE MIKHMAS " },
  { City: "MA'ALE IRON " },
  { City: "MA'ALE AMOS " },
  { City: "MA'ALE SHOMERON " },
  { City: "MA'ALOT-TARSHIHA " },
  { City: "MA'ANIT " },
  { City: "MA'AS " },
  { City: "MEFALLESIM " },
  { City: "MEZADOT YEHUDA " },
  { City: "MAZZUVA " },
  { City: "MAZLIAH " },
  { City: "MIZPA " },
  { City: "MIZPE AVIV " },
  { City: " " },
  { City: "MIZPE YERIHO " },
  { City: "MIZPE NETOFA " },
  { City: "MIZPE RAMON " },
  { City: "MIZPE SHALEM " },
  { City: "MEZER " },
  { City: "MIQWE YISRA'EL " },
  { City: "MARGALIYYOT " },
  { City: "MEROM GOLAN " },
  { City: " " },
  { City: "MERHAVYA(MOSHAV) " },
  { City: "MERHAVYA(QIBBUZ) " },
  { City: "MERKAZ SHAPPIRA " },
  { City: "MASH'ABBE SADE " },
  { City: "MISGAV DOV " },
  { City: "MISGAV AM " },
  { City: "MESHHED " },
  { City: "MASSU'A " },
  { City: "MASSUOT YIZHAQ " },
  { City: "MASKIYYOT " },
  { City: "MISHMAR AYYALON " },
  { City: "MISHMAR DAWID " },
  { City: "MISHMAR HAYARDEN " },
  { City: "MISHMAR HANEGEV " },
  { City: "MISHMAR HAEMEQ " },
  { City: "MISHMAR HASHIV'A " },
  { City: "MISHMAR HASHARON " },
  { City: "MISHMAROT " },
  { City: "MISHMERET " },
  { City: "MASH'EN " },
  { City: "MATTAN " },
  { City: "MATTAT " },
  { City: "MATTITYAHU " },
  { City: "NE'OT GOLAN " },
  { City: "NE'OT HAKIKKAR " },
  { City: "NE'OT MORDEKHAY " },
  { City: "SHIZZAFON " },
  { City: "NA'URA " },
  { City: "NEVATIM " },
  { City: "NEGBA " },
  { City: " " },
  { City: "NEHORA " },
  { City: "NAHALAL " },
  { City: "NAHARIYYA " },
  { City: "NOV  " },
  { City: "NOGAH " },
  { City: "HALLAMISH " },
  { City: "NAVE " },
  { City: "NEWE AVOT " },
  { City: "NEWE UR " },
  { City: "NEWE ATIV " },
  { City: "NEWE ILAN " },
  { City: "NEWE ETAN " },
  { City: "NEWE DANIYYEL " },
  { City: "NEWE ZOHAR " },
  { City: " " },
  { City: "NEWE HARIF " },
  { City: "NEWE YAM " },
  { City: "NEWE YAMIN " },
  { City: "NEWE YARAQ " },
  { City: "NEWE MIVTAH " },
  { City: "NEWE MIKHA'EL " },
  { City: "NEWE SHALOM " },
  { City: "NO'AM " },
  { City: " " },
  { City: "NAZERAT ILLIT " },
  { City: "NOFIM " },
  { City: "NOFIT " },
  { City: "NOFEKH " },
  { City: "NOQEDIM " },
  { City: "NORDIYYA " },
  { City: "NURIT " },
  { City: "NEHUSHA " },
  { City: "NAHAL OZ " },
  { City: "NAHALA " },
  { City: "NAHALI'EL " },
  { City: "NEHALIM " },
  { City: "NAHAM " },
  { City: "NAHEF " },
  { City: "NAHSHOLIM " },
  { City: "NAHSHON " },
  { City: "NAHSHONIM " },
  { City: "NETU'A " },
  { City: "NATUR " },
  { City: "NETA " },
  { City: "NETA'IM " },
  { City: "NATAF " },
  { City: "NEIN " },
  { City: "NILI " },
  { City: "NIZZAN " },
  { City: "NIZZAN B " },
  { City: "NIZZANA (QEHILAT HIN " },
  { City: "NIZZANE SINAY " },
  { City: "NIZZANE OZ " },
  { City: "NIZZANIM " },
  { City: "NIR ELIYYAHU " },
  { City: "NIR BANIM " },
  { City: "NIR GALLIM " },
  { City: "NIR DAWID (TEL AMAL) " },
  { City: "NIR HEN " },
  { City: "NIR YAFE " },
  { City: "NIR YIZHAQ " },
  { City: "NIR YISRA'EL " },
  { City: "NIR MOSHE " },
  { City: "NIR OZ " },
  { City: "NIR AM " },
  { City: "NIR EZYON " },
  { City: "NIR AQIVA " },
  { City: "NIR ZEVI " },
  { City: "NIRIM " },
  { City: "NIRIT " },
  { City: " " },
  { City: "NES HARIM " },
  { City: "NES AMMIM " },
  { City: "NES ZIYYONA " },
  { City: "NE'URIM " },
  { City: "NA'ALE " },
  { City: "NAAMA " },
  { City: "NA'AN " },
  { City: "NIRAN " },
  { City: "NASASRA " },
  { City: " " },
  { City: "NEZER SERENI " },
  { City: "NAZARETH " },
  { City: "NESHER " },
  { City: "NETIV HAGEDUD " },
  { City: "NETIV HALAMED-HE " },
  { City: "NETIV HAASARA " },
  { City: "NETIV HASHAYYARA " },
  { City: "NETIVOT " },
  { City: "NETANYA " },
  { City: "SAJUR " },
  { City: "SASA " },
  { City: "SAVYON " },
  { City: "SEGULA " },
  { City: "SAWA'ID(HAMRIYYE) " },
  { City: "SAWA'ID (KAMANE) " },
  { City: "SULAM " },
  { City: "SUSEYA " },
  { City: "SUFA " },
  { City: "SAKHNIN " },
  { City: "SAYYID " },
  { City: "SALLAMA " },
  { City: "SAL'IT " },
  { City: "SAMAR " },
  { City: " " },
  { City: "SA'AD " },
  { City: " " },
  { City: "SA'AR " },
  { City: "SAPPIR " },
  { City: "SITRIYYA " },
  { City: "GHAJAR " },
  { City: "AVDON " },
  { City: "EVRON " },
  { City: "AGUR " },
  { City: "ADI " },
  { City: "ADANIM " },
  { City: "UZA " },
  { City: "UZEIR " },
  { City: "OLESH " },
  { City: "OMER " },
  { City: "OFER " },
  { City: "OFRA " },
  { City: "OZEM " },
  { City: "UQBI (BANU UQBA) " },
  { City: "EZUZ " },
  { City: "EZER " },
  { City: "AZRI'EL " },
  { City: "AZARYA " },
  { City: "AZRIQAM " },
  { City: "ATAWNE " },
  { City: "ATERET " },
  { City: "IDDAN  " },
  { City: "EILABUN " },
  { City: "AYANOT " },
  { City: "ILUT " },
  { City: "EN AYYALA " },
  { City: "EIN AL-ASAD " },
  { City: "EN GEV " },
  { City: "EN GEDI " },
  { City: "EN DOR " },
  { City: "EN HABESOR " },
  { City: "EN HOD " },
  { City: "EN HAHORESH " },
  { City: "EN HAMIFRAZ " },
  { City: "EN HANAZIV " },
  { City: "EN HAEMEQ " },
  { City: "EN HASHOFET " },
  { City: "EN HASHELOSHA " },
  { City: "EN WERED " },
  { City: "EN ZIWAN " },
  { City: " " },
  { City: "EN HAZEVA " },
  { City: "EN HAROD (IHUD) " },
  { City: "EN HAROD(ME'UHAD) " },
  { City: "EN YAHAV " },
  { City: "EN YA'AQOV " },
  { City: "EN KAREM-B.S.HAQLA'I " },
  { City: "EN KARMEL " },
  { City: "EIN MAHEL " },
  { City: "EIN NAQQUBA " },
  { City: "EN IRON " },
  { City: "EN ZURIM " },
  { City: "EIN QINIYYE " },
  { City: "EIN RAFA " },
  { City: "EN SHEMER " },
  { City: "EN SARID " },
  { City: "EN TAMAR " },
  { City: "ENAT " },
  { City: "IR OVOT " },
  { City: "AKKO " },
  { City: "ALUMIM " },
  { City: "ELI " },
  { City: "ALE ZAHAV " },
  { City: "ALMA " },
  { City: "ALMON " },
  { City: "AMUQQA " },
  { City: " " },
  { City: "AMMINADAV " },
  { City: "AMMI'AD " },
  { City: "AMMI'OZ " },
  { City: "AMMIQAM " },
  { City: "AMIR " },
  { City: "IMMANU'EL " },
  { City: "AMQA " },
  { City: "ENAV " },
  { City: "ISIFYA " },
  { City: "AFULA " },
  { City: "EZ EFRAYIM " },
  { City: "ATSMON-SEGEV " },
  { City: "ARRABE " },
  { City: "ARAMSHA " },
  { City: "ARRAB AL NAIM " },
  { City: "ARAD " },
  { City: "ARUGOT " },
  { City: "AR'ARA " },
  { City: "AR'ARA-BANEGEV " },
  { City: "ASERET " },
  { City: "ATLIT " },
  { City: "OTNI'EL " },
  { City: "PARAN " },
  { City: "PEDU'EL " },
  { City: "PEDUYIM " },
  { City: "PEDAYA " },
  { City: "PORIYYA-KEFAR AVODA " },
  { City: "PORIYYA-NEWE OVED " },
  { City: "PORIYYA ILLIT " },
  { City: "FUREIDIS " },
  { City: "PORAT " },
  { City: "PATTISH " },
  { City: "PELEKH " },
  { City: "PALMAHIM " },
  { City: "PENE HEVER " },
  { City: "PESAGOT " },
  { City: "FASSUTA " },
  { City: "PA'AME TASHAZ " },
  { City: "PEZA'EL " },
  { City: "PEQI'IN (BUQEI'A) " },
  { City: "PEQI'IN HADASHA " },
  { City: "PARDES HANNA-KARKUR " },
  { City: "PARDESIYYA " },
  { City: "PAROD " },
  { City: "PERAZON " },
  { City: "PERI GAN " },
  { City: "PETAH TIQWA " },
  { City: "PETAHYA " },
  { City: "ZE'ELIM " },
  { City: "ZVIYYA " },
  { City: "ZIV'ON " },
  { City: "ZOVA " },
  { City: "ZOHAR " },
  { City: "ZOFIYYA " },
  { City: "ZUFIN " },
  { City: "ZOFIT " },
  { City: "ZOFAR " },
  { City: "SHOSHANNAT HAAMAQIM( " },
  { City: "MAHANE BILDAD " },
  { City: "ZUR HADASSA " },
  { City: "ZUR YIZHAQ " },
  { City: "ZUR MOSHE " },
  { City: "ZUR NATAN " },
  { City: "ZURI'EL " },
  { City: "ZURIT " },
  { City: "ZIPPORI " },
  { City: "ZELAFON " },
  { City: "SANDALA " },
  { City: "ZAFRIYYA " },
  { City: "ZAFRIRIM " },
  { City: "ZEFAT " },
  { City: "ZERUFA " },
  { City: "ZOR'A " },
  { City: "QABBO'A " },
  { City: "QEVUZAT YAVNE " },
  { City: "QEDUMIM " },
  { City: "QADIMA-ZORAN " },
  { City: "QEDMA " },
  { City: "QIDMAT ZEVI " },
  { City: "QEDAR " },
  { City: "QIDRON " },
  { City: "QADDARIM " },
  { City: "QUDEIRAT AS-SANI " },
  { City: "QAWA'IN " },
  { City: "QOMEMIYYUT " },
  { City: "QORANIT " },
  { City: "QETURA " },
  { City: "QESARIYYA " },
  { City: "QELAHIM " },
  { City: "QALYA " },
  { City: "QALANSAWE " },
  { City: "QELA " },
  { City: " " },
  { City: " " },
  { City: "QAZRIN " },
  { City: "QIRYAT ONO " },
  { City: "QIRYAT ARBA " },
  { City: "QIRYAT ATTA " },
  { City: "QIRYAT BIALIK " },
  { City: "QIRYAT GAT " },
  { City: "QIRYAT TIV'ON " },
  { City: "QIRYAT YAM " },
  { City: "QIRYAT YE'ARIM " },
  { City: "QIRYAT YE'ARIM(INSTI " },
  { City: "QIRYAT MOTZKIN " },
  { City: "QIRYAT MAL'AKHI " },
  { City: "QIRYAT NETAFIM " },
  { City: "QIRYAT ANAVIM " },
  { City: "QIRYAT EQRON " },
  { City: "QIRYAT SHELOMO " },
  { City: "QIRYAT SHEMONA " },
  { City: "QARNE SHOMERON " },
  { City: "QESHET " },
  { City: "RAME " },
  { City: " " },
  { City: "RAS ALI " },
  { City: "ROSH HAAYIN " },
  { City: "ROSH PINNA " },
  { City: "ROSH ZURIM " },
  { City: "RISHON LEZIYYON " },
  { City: "REVAVA " },
  { City: "REVADIM " },
  { City: "REVIVIM " },
  { City: "RAVID " },
  { City: "REGBA " },
  { City: "REGAVIM " },
  { City: "RAHAT " },
  { City: "REWAHA " },
  { City: "REWAYA " },
  { City: " " },
  { City: "RUHAMA " },
  { City: "RUMMANE " },
  { City: "RUMAT HEIB " },
  { City: "RO'I " },
  { City: "ROTEM " },
  { City: "REHOV " },
  { City: "REHOVOT " },
  { City: " " },
  { City: "REIHANIYYE " },
  { City: "REHAN " },
  { City: "REINE " },
  { City: "RIMMONIM " },
  { City: "RINNATYA " },
  { City: "REKHASIM " },
  { City: "RAM-ON " },
  { City: "RAMOT " },
  { City: "RAMOT HASHAVIM " },
  { City: "RAMOT ME'IR " },
  { City: "RAMOT MENASHE " },
  { City: "RAMOT NAFTALI " },
  { City: "RAMLA " },
  { City: "RAMAT GAN " },
  { City: "RAMAT DAWID " },
  { City: "RAMAT HAKOVESH " },
  { City: "RAMAT HASHOFET " },
  { City: "RAMAT HASHARON " },
  { City: "RAMAT YOHANAN " },
  { City: "RAMAT YISHAY " },
  { City: "RAMAT MAGSHIMIM " },
  { City: "RAMAT ZEVI " },
  { City: "RAMAT RAZI'EL " },
  { City: "RAMAT RAHEL " },
  { City: "RANNEN " },
  { City: "RE'IM " },
  { City: "RA'ANANA " },
  { City: "RAQEFET " },
  { City: "RISHPON " },
  { City: "RESHAFIM " },
  { City: "RETAMIM " },
  { City: "SHE'AR YASHUV " },
  { City: " " },
  { City: "SHAVE ZIYYON " },
  { City: "SHAVE SHOMERON " },
  { City: "SHIBLI " },
  { City: "SEGEV-SHALOM " },
  { City: "SEDE ILAN " },
  { City: "SEDE ELIYYAHU " },
  { City: "SEDE ELI'EZER " },
  { City: "SEDE BOQER " },
  { City: "SEDE DAWID " },
  { City: "SEDE WARBURG " },
  { City: "SEDE YO'AV " },
  { City: "SEDE YA'AQOV " },
  { City: "SEDE YIZHAQ " },
  { City: "SEDE MOSHE " },
  { City: "SEDE NAHUM " },
  { City: "SEDE NEHEMYA " },
  { City: "SEDE NIZZAN " },
  { City: "SEDE UZZIYYAHU " },
  { City: "SEDE ZEVI " },
  { City: "SEDOT YAM " },
  { City: "SEDOT MIKHA " },
  { City: "SEDE AVRAHAM " },
  { City: "SEDE HEMED " },
  { City: "SEDE TERUMOT " },
  { City: "SHEDEMA " },
  { City: "SHADMOT DEVORA " },
  { City: "SHADMOT MEHOLA " },
  { City: "SEDEROT " },
  { City: "SHO'EVA " },
  { City: "SHUVA " },
  { City: "SHOVAL " },
  { City: "SHOHAM " },
  { City: "SHOMERA " },
  { City: "SHOMERIYYA " },
  { City: "SHOQEDA " },
  { City: "SHORESH " },
  { City: "SHORASHIM " },
  { City: "SHOSHANNAT HAAMAQIM " },
  { City: "SHEZOR " },
  { City: "SHAHAR " },
  { City: "SHAHARUT " },
  { City: "SHIBBOLIM " },
  { City: "NAHAL SHITTIM " },
  { City: "SHEIKH DANNUN " },
  { City: "SHILO " },
  { City: "SHILAT " },
  { City: "SHEKHANYA " },
  { City: "SHALWA " },
  { City: "SHALVA BAMIDBAR " },
  { City: "SHELUHOT " },
  { City: "SHELOMI " },
  { City: " " },
  { City: "SHAMIR " },
  { City: "SHIM'A " },
  { City: "SHAMERAT " },
  { City: " " },
  { City: "SHANI " },
  { City: "SENIR " },
  { City: "SHA'AB " },
  { City: "SE'ORIM " },
  { City: "SHA'AL " },
  { City: "SHA'ALVIM " },
  { City: "SHA'AR EFRAYIM " },
  { City: "SHA'AR HAGOLAN " },
  { City: "SHA'AR HAAMAQIM " },
  { City: "SHA'AR MENASHE " },
  { City: "SHA'ARE TIQWA " },
  { City: "SHEFAYIM " },
  { City: "SHAFIR " },
  { City: "SHEFER " },
  { City: "SHEFAR'AM " },
  { City: "SHAQED " },
  { City: "SHEQEF " },
  { City: "SHARONA " },
  { City: "LI-ON " },
  { City: "SARID " },
  { City: "SHARSHERET " },
  { City: "SHETULA " },
  { City: "SHETULIM " },
  { City: "TE'ASHUR " },
  { City: "TIDHAR " },
  { City: "TUVAL " },
  { City: "TOMER " },
  { City: "TUSHIYYA " },
  { City: "TIMMORIM " },
  { City: "TIROSH " },
  { City: "TEL AVIV - YAFO " },
  { City: "TEL YOSEF " },
  { City: "TEL YIZHAQ " },
  { City: "TEL MOND " },
  { City: "TEL ADASHIM " },
  { City: "TEL QAZIR " },
  { City: "TEL SHEVA " },
  { City: "TEL TE'OMIM " },
  { City: "TELEM " },
  { City: "TALME ELIYYAHU " },
  { City: "TALME EL'AZAR " },
  { City: "TALME BILU " },
  { City: "TALME YOSEF " },
  { City: "TALME YEHI'EL " },
  { City: "TALME YAFE " },
  { City: "TELAMIM " },
  { City: "TIMRAT " },
  { City: "TENUVOT " },
  { City: "TA'OZ " },
  { City: "TIFRAH " },
  { City: "TEQUMA " },
  { City: "TEQOA " },
  { City: "TARABIN AS-SANI " },
  { City: " " },
  { City: "TARUM " },
  { City: "" },
];
